name: Build and publish page
on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build and deploy GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUBTOKEN }}
          cname: kopenhagen-westfalens.de
