name: Build and publish page
on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build and deploy GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: "peaceiris/actions-hugo@v2"
        with:
          hugo-version: '0.72.0'

      - name: Build
        run: hugo --minify --gc --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          publish_dir: ./public
